import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { ProductProvider } from "./context/ProductContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Test",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ProductProvider>
          <Navbar />
          {children}
        </ProductProvider>
      </body>
    </html>
  );
}
